#!/usr/bin/bash

set -e

PROGRAM=$(basename $0)

function git_is_clean() {
    [ -z "$(git status --porcelain | grep -v '??')" ] &>/dev/null
}

function git_is_up2date() {
    git rev-list --count --left-right 'HEAD...@{upstream}' | grep -qP '^\s*0\s+0\s*$'
}

function error() {
    echo "$PROGRAM: $@"
    echo "Usage: $PROGRAM VERSION [RELEASE-NOTES]"
    exit 1
} >&2

[ $# = 1 -o $# = 2 ] || error "Illegal number of arguments"
VERSION=$1
TAG=v$VERSION
TITLE="Release $VERSION"
NOTES="$2"

git_is_clean || error "Repository is dirty"
git_is_up2date || error "Repository is not synchronized with origin"

if [ -z "$NOTES" ]; then
    echo "Enter release notes and end with CTRL+D"
    cat
else
    echo $NOTES
fi \
| gh release create $TAG \
    --notes-file=/dev/stdin \
    --title="$TITLE"
