#!/usr/bin/env ruby

require_relative '../lib/qrpm/qrpm.rb'
require_relative '../lib/qrpm.rb'

require 'yaml'
require 'shellopts'
require 'indented_io'

# TODO
#   o Make option
#   o Fix BuildRoot (contains absolute path)

begin
  SPEC = %(
    @ Quick RPM builder

    'qrpm' creates a RPM package from a simple YAML specification file

    -- VARIABLE=VALUE... QRPM-FILE

    -s,spec
      Only create the spec file and not the RPM package

    -f,force
      Create package even if repository is dirty

    -C,directory=DIR
      Change to directory before doing anything else
  )

  opts, args = ShellOpts.process(SPEC, ARGV)

  Dir.chdir(opts.directory) if opts.directory?

  file = args.extract(-1)
  dict = {} # Map from variable name to value

  # Check if repository is clean
  opts.force? || `git status --porcelain 2>/dev/null` == "" or raise "Repository is dirty"

  # Collect command line variable settings
  args.each { |expr|
    expr =~ /^(.*?)=(.*)$/ or raise "Illegal expression: '#{expr}'"
    dict[$1] = $2
  }

  yaml = YAML.load(IO.read(file).sub(/^__END__.*/m, ""))

  # Parse QRPM file
  rpm = Qrpm::Parser.parse(dict, yaml)

# rpm.dump

  subject = (opts.spec? ? :spec : :all)
  rpm.build(subject: subject)


rescue RuntimeError => ex
  ShellOpts.error ex.message
end

