#!/usr/bin/env ruby

#$LOAD_PATH.unshift "/home/clr/prj/shellopts/lib"

require_relative '../lib/qrpm/qrpm.rb'
require_relative '../lib/qrpm.rb'

require 'yaml'
require 'shellopts'

# TODO
#   o Fix BuildRoot (contains absolute path)
#
#   + Separate standard variables from user-variables in dump
#   + Enable escape of $
#   + Support for $(...) constructs

begin
  SPEC = %(
    @ Make simple RPMs simple

    -- VARIABLE=VALUE... [QRPM-FILE]

    'qrpm' creates a RPM package from a qrpm.yml specification file. It aims at
    packaging shell scripts or simple executables/libraries with minimum effort

    The qrpm.yml specification file is a YAML file. The simplest qrpm file
    contains just one line:

      $bindir: my_executable_script

    Running qrpm using this file will yield a RPM package that installs the
    script into the standard /usr/bin directory. The name of the package
    is set to the name of the current directory and version to the latest tag
    in git (which needs to be present). Other defaults are detailed below

    SETUP
      Use qrpm -t to generate a template qrpm.yml file:

        qrpm -t [TEMPLATE-FILE]

      Then customize as needed

    VARIABLES
      The configuration file can define and use variables. They are defined by
      key/value definitions and the value can refer to values of other
      variables using $NAME or ${NAME}. Variables can also be given on the
      command line in <variable>=<value> format

      $(...) constructs are commands that are executed by bash(1). The parser
      considers everything from the opening '$(' to the last ')' on the line as
      part of the command so only one command is allowed. This restriction keeps
      the parser simple, it may change in the future

    STANDARD VARIABLES
      The following RPM variables are recognized. They all have defaults:

        name
          Name of the package. Default is the name of the current directory

        version
          Version number. The default is extracted from the newest tag/branch
          in the git history. See VERSIONS below

        version_file
          File that is scanned for the version. An alternative to 'version'

        release
          Build number of this version of the package. It is appended to the
          version in the package name (eg. 1.2.3-1) and is incremented when the
          package is rebuilt without changing the version. Default 1

        summary
          A short one-line text. Default 'The <name> RPM package'

        description
          A longer multiline text. Default is the summary

        packager
          Packager name. Default the current user

        license
          License of the package. Default GPL

        require
          List of required RPM packages

    ROUTINES
      Routines are shell scripts that run when the package is built or when
      it is installed or uninstalled. They are not interpolated. Instead the
      qrpm variables they refer to as $name or ${name} are defined as shell
      variables at the top of the script, so shell variables like $HOME,
      positional parameters like $1, and $(...) constructs work as usual.
      Variable names can't start with a digit for that reason:

        make
          Runs on the build host in the source directory when the package is
          built

        pre
          Runs on the installation host before the package is installed

        post
          Runs on the installation host after the package is installed

        pre_uninstall
          Runs on the installation host before the package is uninstalled

        post_uninstall
          Runs on the installation host after the package is uninstalled

    BUILT-IN VARIABLES
      There are the following built-in variables. They are listed below with their
      default values. Note that rootdir is a prefix of all other directories and
      not a directory in itself, it is empty by default

        rootdir
        rootconfdir     /etc
        rootexecdir     /usr
        rootbindir      /bin
        rootsbindir     /sbin
        rootlibdir      /usr
        rootconstdir    /usr/share
        rootdocdir      /usr/share
        rootdatadir     /var

      The system directories are the standard directories of the system:

        sysetcdir       /etc
        sysbindir       /bin
        syssbindir      /sbin
        syslibdir       /usr/lib64
        syslibexecdir   /usr/libexec
        syssharedir     /usr/share
        sysdocdir       /usr/share/doc
        sysvardir       /var/lib
        sysspooldir     /var/spool
        sysrundir       /var/run
        syslockdir      /var/lock
        syscachedir     /var/cache
        syslogdir       /var/log
        systmpdir       /tmp

      The package directories are subdirectories of the system directories
      named after the package. There are no package specific directories for
      bin and sbin:

        pcketcdir       /etc/NAME
        pckbindir       /bin
        pcksbindir      /sbin
        pcklibdir       /usr/lib64/NAME
        pcklibexecdir   /usr/libexec/NAME
        pcksharedir     /usr/share/NAME
        pckdocdir       /usr/share/doc/NAME
        pckvardir       /var/lib/NAME
        pckspooldir     /var/spool/NAME
        pckrundir       /var/run/NAME
        pcklockdir      /var/lock/NAME
        pckcachedir     /var/cache/NAME
        pcklogdir       /var/log/NAME
        pcktmpdir       /tmp/NAME

    VERSIONS
      The version is searched for in the git history of the source directory
      when the qrpm file has no 'version' field. The highest version among
      the tags reachable from HEAD wins. If there is none, the name of the
      current branch is used. It is an error if no version is found, add a
      'version' field in that case

      A tag or branch looks like a version if it is a semantic version with
      the usual quirks: an optional prefix like 'release-' or 'release/', an
      optional 'v', a pre-release suffix like '-rc1' or '.beta2', and build
      metadata after '+'. Only the version and the pre-release suffix are
      used and the suffix is separated with '~' so that rpm orders it before
      the final version, eg. 'v2.0.0-rc1' becomes '2.0.0~rc1'

      'version_file' names a file relative to the source directory that is
      scanned for a version instead of searching the git history. The first
      version that follows the word 'version' wins, as in VERSION = "1.2.3"
      or __version__ = '1.2.3', so that other dotted numbers in the file are
      skipped. If there is none, the first version-like token (with at least
      one dot) in the file is used. It can't be used together with
      'version':

        version_file: lib/mypackage/version.rb

    INSTALLATION DIRECTORIES
      The root directories are the prefixes that the system directories are
      derived from. They correspond to the prefix variables of autoconf:
      rootconfdir is sysconfdir, rootexecdir is exec_prefix (the root of the
      architecture dependent files bin, sbin, lib and libexec), rootconstdir
      is datarootdir, and rootdatadir is localstatedir. rootdir is a prefix
      of all other directories and not a directory in itself. It is empty by
      default. rootbindir and rootsbindir are /bin and /sbin, but on systems
      where those are symbolic links (merged /usr) they are the directories
      the links point to, typically /usr/bin and /usr/sbin:

    INCLUDE FILES
      The qrpm file can include other files that are searched for in a list of
      directories. Relative paths are relative to the directory of the qrpm file
      (but see the -C option). The search directories can be set on the command
      line using the -I option

    OPTIONS
      -f,force
        Create package even if repository is dirty. Normally qrpm checks if the
        current (git) directory is clean

      -C,directory=EDIR
        Change to directory before doing anything else but include the current
        directory in the search path. This makes it possible to override parts of
        a spec file

      +I,include=EDIR
        Include directory, later definitions are searched first

      -s,spec=OFILE?
        Only create the spec file and not the RPM package. Use this option to
        inspect what RPM is going to do

      -S,source
        Create a source RPM file instead of a regular RPM file

      -t,template=OFILE?
        Generate a QRPM template. It is in YAML format with the extension that a
        single '__END__' terminates the file immediately. The name of the file
        defaults to 'qrpm.yml'. It is an error if the file exists

      -T,force-template=OFILE?
        Like --template but overwrites file if it exists

      -b,builddir=NPATH?
        Use the given path as the RPM build dir, default is 'builddir'. Doesn't
        remove the directory afterwards. It it is an error if the directory exists

      -B,force-builddir=PATH?
        Like --builddir but overwrites the directory if it exists beforehand

      --target=TARGET
        Build the package for another system. The target selects rpm macros
        that make the package installable there and is appended to the
        release, eg. 1.el7, so that the package file shows what it was built
        for. The only target is 'el7' (CentOS/RHEL 7), which makes rpmbuild use
        a gzip payload because rpm 4.11 can't read the default zstd payload

      -d,dump
        Dump internal data and exit. For debug

    COMMANDS
      show! -- QRPM-FILE VARIABLE...
        Output the value of a variable. Typically used to extract the version
        number from a qrpm.yml file
  )

  opts, args = ShellOpts.process(SPEC, ARGV, verbose: true, quiet: true)

  if opts.template? || opts.force_template?
    outfile = opts.template || opts.force_template || Qrpm::QRPM_CONFIG_FILE
    opts.force_template? || !File.exist?(outfile) or ShellOpts.error "Won't overwrite existing file: #{outfile}"
    FileUtils::cp Qrpm::QRPM_CONFIG_FILE_TEMPLATE, outfile
    puts "Generated #{outfile}" if !opts.quiet?
    exit
  end

  # Process arguments. The overrides hash is constructed from var=val arguments
  # on the command line
  overrides = {}
  file = nil
  show = []
  while arg = args.extract(0..1)
    if arg =~ /^(.*?)=(.*)$/
      overrides[$1] = $2
    elsif file.nil?
      file = arg
    elsif opts.subcommand == :show!
      show << arg
    else
      args.expect(-1, "More than one file argument")
    end
  end
  args.expect(0)

  # Compute/normalize currdir and qrpmdir and add them to the dictionary
  currdir = overrides["currdir"] = File.expand_path(overrides["currdir"] || Dir.getwd)
  qrpmdir = overrides["qrpmdir"] = File.expand_path(overrides["qrpmdir"] || opts.directory || ".")

  # Check builddir (todo: also currdir?)
  File.directory?(currdir) or error "Can't find '#{currdir}'"
  File.directory?(qrpmdir) or error "Can't find '#{qrpmdir}'"

  # Compute builddir
  if opts.builddir? && opts.force_builddir?
    ShellOpts.error "Can't use both --builddir and --force-builddir"
  elsif opts.builddir? || opts.force_builddir?
    builddir = opts.builddir || opts.force_builddir || "builddir"
    opts.force_builddir? || !File.exist?(builddir) or
        ShellOpts.error "Build directory 'builddir' exists - use -B to override"
    builddir = File.expand_path(builddir)
  else
    builddir = nil
  end

  # Check if repository is clean. Only changes below the qrpm directory count
  opts.force? || opts.dump? || !Qrpm.dirty?(qrpmdir) or ShellOpts.error "Repository is dirty"

  # Create lexer
  lexer = Qrpm::Lexer.new([currdir, qrpmdir].uniq, opts.include.reverse)

  # Change to qrpm directory
  Dir.chdir(qrpmdir)

  # Check configuration file
  file ||= Qrpm::QRPM_CONFIG_FILE
  ::File.exist?(file) or ShellOpts.error "Can't find '#{file}'"

  # Load the qrpm configuration file
  conf = lexer.lex(File.expand_path file)

  # Parse QRPM configuration file. Include paths are still resolved with the
  # context of the original directory if -C is used while filesystem paths are
  # relative to the source directory
  compiler = Qrpm::Compiler.new(overrides)
  qrpm = compiler.compile(conf)
  # Check target
  opts.target.nil? || Qrpm::Rpm::TARGETS.key?(opts.target) or
      ShellOpts.error "Unknown target '#{opts.target}', use one of #{Qrpm::Rpm::TARGETS.keys.join(", ")}"

  rpm = qrpm.rpm(target: opts.target)

  if opts.subcommand == :show!
    for variable in show
      puts qrpm[variable]
    end
    exit
  end

  if opts.dump?
    puts "Compiler"
    indent { compiler.dump }

    puts "Qrpm"
    indent { qrpm.dump_parts }

    puts "Rpm"
    indent { rpm.dump }

    exit
  end

  # Create spec/srpm/rpm file
  target = (opts.spec? ? :spec : (opts.source? ? :srpm : :rpm))
  files = rpm.build(
      target: target,
      file: opts.spec,
      verbose: opts.verbose?,
      destdir: currdir,
      builddir: builddir)

  puts "Built #{files.map { |f| File.basename(f) }.join(" ")}" if !opts.quiet?

rescue RuntimeError, Qrpm::CompileError => ex
  ShellOpts.failure ex.message
end

